#ifndef _PUBLISHTHIRDPARTYMESSAGERESPONSEHANDLER
#define _PUBLISHTHIRDPARTYMESSAGERESPONSEHANDLER
#include "PublishThirdPartyMessageResponse.h"

#include "FastDelegate.h"
typedef fastdelegate::FastDelegate1<PublishThirdPartyMessageResponse*>PublishThirdPartyMessageResponseHandler;

#endif // _PUBLISHTHIRDPARTYMESSAGERESPONSEHANDLER